
# can use #DF6589 INSTEAD OF RED #3C1053  
# [](#3C1053)[ ](bg:#3C1053 fg:#DF6589)[](#3C1053) : \
# [](#2b303a)[  ](bg:#2b303a fg:#ff934f)[](#2b303a) : \
format = """
[ :](#3E92CC) \
$username\
$directory\
$git_branch\
$git_status\
$c\
$golang\
$java\
$julia\
$rust\
$python\
$conda\
$docker_context\
$cmd_duration\
$character
"""

add_newline = true

[cmd_duration]
style = "bold fg:#b472ed"
min_time = 500
format = "[took $duration]($style) "

[c]
detect_extensions = ["c", "h", "cpp", "hpp"]
commands = [ [ "cc", "--version" ], [ "gcc", "--version" ], [ "clang", "--version" ], [ "g++", "--version" ], [ "clang++", "--version" ] ]
symbol = " "

[conda]
style = "bg:#f72585 fg:#000000"
symbol = " "
format = "via [](#f72585)[$symbol$environment]($style)[](#f72585) "

[character] # The name of the module we are configuring is "character"
success_symbol = "[➜](bold #daff7d)"  # "[❯](bold cyan)[❯](bold green)" # "[➜](bold #daff7d)" #caffbf #9bf6ff
error_symbol = "[➜](bold #ee7674)"    # "[❯](bold yellow)[❯](bold red)" # "[➜](bold #ee7674)" #ffd6a5 #ffadad

[directory]
style = "fg:#faedcb" #DABFFF
truncation_length = 2
home_symbol = "( \uE12C )"
truncation_symbol = "~/•/"
read_only = " "

[directory.substitutions]
"Documents" = "#DOCS"
"Downloads" = "#DOWNLOADS"
"Music" = "#MUSIC"
"Pictures" = "#PICTURES"


[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "  #""
style = "bold fg:#b5f04f"
format = '[git:\(](bold blue)[$symbol$branch]($style)'

[git_status]
style = "bold fg:#b5f04f"
format = '[$all_status$ahead_behind]($style)[\)](bold blue) '


[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = " "

[meson]
symbol = "喝 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "
style = "bold bg:yellow fg:#212121"
format = '[](yellow)[$symbol($version)]($style)[](yellow) '
pyenv_prefix = ":pyenv:"

[rlang]
symbol = "ﳒ "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

