format = """
[ :](#3E92CC) \
$username\
$directory\
$git_branch\
$git_status\
$c\
$golang\
$java\
$julia\
$rust\
$python\
$conda\
$docker_context\
$cmd_duration\
$character
"""

add_newline = true

[cmd_duration]
style = "bold bright-purple"
min_time = 500
format = "[took $duration]($style) "

[c]
detect_extensions = ["c", "h", "cpp", "hpp"]
commands = [ [ "cc", "--version" ], [ "gcc", "--version" ], [ "clang", "--version" ], [ "g++", "--version" ], [ "clang++", "--version" ] ]
symbol = " "

[conda]
style = "bg:#f72585 fg:#000000"
symbol = " "
format = "via [](#f72585)[$symbol$environment]($style)[](#f72585) "

[character] # The name of the module we are configuring is "character"
success_symbol = " [➜](bold #daff7d)"  # "[❯](bold cyan)[❯](bold green)" # "[➜](bold #daff7d)" #caffbf #9bf6ff
error_symbol = " [➜](bold bright-red)"    # "[❯](bold yellow)[❯](bold red)" # "[➜](bold #ee7674)" #ffd6a5 #ffadad

[directory]
style = "bright-yellow" #DABFFF
truncation_length = 2
home_symbol = "[~]"
truncation_symbol = "~/•/"
read_only = " "

[directory.substitutions]
"Documents" = "󱧶"
"Downloads" = "󰉍"
"Music" = "󱍙"
"Pictures" = "󰉏"

[docker_context]
symbol = " "
format = 'via [$symbol$context]($style) '
style = "bold blue"
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
disabled= false

[git_branch]
symbol = " "  #""
style = "bold fg:#b5f04f"
format = '[git:\(](bold blue)[$symbol$branch]($style)'

[git_status]
style = "bold fg:#b5f04f"
format = '[$all_status$ahead_behind]($style)[\)](bold blue) '

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[nodejs]
symbol = " "

[python]
symbol = " "
style = "bold bg:yellow fg:#212121"
format = '[](yellow)[$symbol($version)]($style)[](yellow) '
pyenv_prefix = ":pyenv:"

[rust]
symbol = " "

